import { Component } from "@angular/core";
import { IonHeader, IonToolbar, IonTitle, IonContent } from "@ionic/angular/standalone";
import { WindowCardComponent } from "../components/window-card/window-card.component";
import { CommonModule } from "@angular/common";

@Component({
	selector: "app-home",
	templateUrl: "home.page.html",
	styleUrls: ["home.page.scss"],
	imports: [IonHeader, IonToolbar, IonTitle, IonContent, WindowCardComponent, CommonModule],
})
export class Home {
	constructor() {}

	myArray = [
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
		{
			window_nameCode: "typeC",
			imageUrl: "https://picsum.photos/800/450",
			content: "Description for card 1...",
			nameCode: "type1",
			width_ft: 2,
			width_in: 5,
			height_ft: 6,
			height_in: 7,
			captured_at: "2025-10-29 10:00",
			latitude: `48° 51\' 29" N`,
			longitude: `2° 17\' 40" E`,
			image_uri: "",
			thumb_uri: "",
		},
	];
}
